### ISSUE TITLE
Library should be able to add pre and post processes callbacks

### ISSUE THREAD

**Issue by wighawag** [Kode/khamake#103]
Following up on https://github.com/Kode/khamake/issues/34
it would be great to allow libraries to add pre process and post process step.
Maybe they could even have write access to the project object so they can add stuff

Not sure how this could be done but maybe a khafile.js per library that would in some way allow to pass callbacks ?

**Comment by RobDangerous** [comment]
Hey, this should work with the new addProject function.

**Comment by wighawag** [comment]
Cool, any documentation on it somewhere?

**Comment by RobDangerous** [comment]
Of course, I always document every detail of Kha! See https://github.com/Kode/Kha/wiki/khafile.js#add-a-subproject and https://github.com/Kha-Samples/SubProjects

**Comment by wighawag** [comment]
sub projects are cool but is there any reason to not have included the functionality in libraries ?
Having 2 ways to add external code/assets to a project could be confusing
