### ISSUE TITLE
android-native: second run of khamake taking to much time

### ISSUE THREAD

**Issue by JeriXNet** [Kode/khamake#11]
When I first run khamake for android native it takes 9 seconds. But second and other times it takes almost 2 minutes. I workaround this in script by deleting this dirs:

```
android_native_build/prj_name/app/src/main/jni
android_native_build/Sources
```

**Comment by RobDangerous** [comment]
That's because it checks the files for differences and overrides only changed files - which can speed up C++ compilation a lot. Will see if I can speed that up.

**Comment by RobDangerous** [comment]
Ah, this is fixed due to the switch to cmake for Android.
