### ISSUE TITLE
Access data from command line inside the khafile

### ISSUE THREAD

**Issue by wighawag** [Kode/khamake#114]
Currently there is no way to do something in the khafile that depends on command line arguments
It would be great to be able to access the command line arguments from the khafile so it can act on them

The custom target thing does not currently allow khafile to know about the custom target.

I also think something different than custom target should be used to access any kind of arguments

**Comment by sh-dave** [comment]
For custom targets, you should be able to use the ```platform``` to get it.

khafile.js
```
console.log(platform);
```

```node Kha/make html-9000``` prints ```html-9000```

**Comment by wighawag** [comment]
Cool, did not figure that out from the code. That will help for my current use case

Leaving it open though as it would be better to have a mechanism to access the full command line argument so options can be given to khafile
