### ISSUE TITLE
Honor graphics option for Krom

### ISSUE THREAD

**Issue by luboslenco** [Kode/khamake#118]
This patch: https://github.com/Kode/khamake/pull/101
Got reverted in this commit: https://github.com/Kode/khamake/commit/571138cb6a7e3eee7cdc9e41ae52cf8cea1a0908#diff-75b50b3820b05967e723e942f965bbce

Unfortunately there is now no way to compile for Krom using desired graphics API. Is there a way to restore this? Was this option causing trouble?

**Comment by RobDangerous** [comment]
It's back and now it's really shiny.

**Comment by luboslenco** [comment]
Yay, thanks!
