### ISSUE TITLE
Option in khafile.js to specify additional include directory for c++ target.

### ISSUE THREAD

**Issue by montonero** [Kode/khamake#120]
My kha project has some functionality implemented in c++, hence when building with kha-make I would like to tell it to include additional directories so it could generate correct project files.
Currently I need to modify generated project files manually.

**Comment by luboslenco** [comment]
Does this help?
https://github.com/luboslenco/kha_cppexterns
https://github.com/luboslenco/kha_callcpp
https://github.com/luboslenco/kha_calldll

Or a more real-world usage:
https://github.com/armory3d/haxebullet

**Comment by montonero** [comment]
Thanks, Lubos! I moved my code into Library as your kha_cppexterns sample does and all works fine.
