### ISSUE TITLE
[Proposal] Enhance haxe compiler output

### ISSUE THREAD

**Issue by riseremi** [Kode/khamake#125]
Context:
`node ../Kha/make html5 -watch`

Watch server says `Haxe compile end.` both on fail and success. I suggest to change the output based on rebuild status.

**Successful rebuilds**
```
Haxe: Compiled successfully.
Time: 458ms
```

**Failed rebuilds**
```
Haxe: Failed to compile.
systems/MotionSystem.hx:22: characters 40-45 : Unknown identifier : scast
```

There is also an error about unhandled promise rejection that can be fixed in this scope (catch `triggerCompilationServer` promise result):
```
(node:16159) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Haxe compiler error (code: 1)
(node:16159) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Please let me know if this sounds good, so I can submit a PR.

**Comment by RobDangerous** [comment]
That sounds very good.
