### ISSUE TITLE
Provide a way to skip asset list creation in kha.Assets

### ISSUE THREAD

**Issue by sh-dave** [Kode/khamake#135]
Projects not necessarily need access to the embedded asset lists. In our case, we only load assets via kha.Assset.loadFromPath() so everything in these lists is superfluous, but these 1500 assets increase the generated `kha.js` filesize from `1.2mb` to `2.6mb` in html5 builds, and won't even compile in windows debug builds without workarounds, see #133.

So the new option would convert assets as usual, but wouldn't add fields to the internal kha.Assets lists.
This could ideally be set for each `prj.addAssets()` call in khafile.js. In our case, i'd only exclude the first 2 calls from the following example.

```js
project.addAssets('assets/**');
project.addAssets('assets-highres/**');
project.addAssets('assets-ui/**', { nameBaseDir: 'assets-ui', destination: '{dir}/{name}', name: '{dir}/{name}' });
project.addAssets('settings/**');
```

**Comment by RobDangerous** [comment]
Done, use the new notinlist option like so:

```javascript
project.addAssets('Assets/Music/*', { quality: 0.5, notinlist: true });
```
