### ISSUE TITLE
Source code not recompiled on change

### ISSUE THREAD

**Issue by carlito767** [Kode/khamake#155]
Hi,

I recently updated my project to the latest Kha and the source code is not recompiled on change anymore. Here is the batch file used to build the project:

> pushd ..
> start /B node Kha/make html5 --watch
> start /B node Kha/make --server
> popd

It seems related to this [revision](https://github.com/Kode/khamake/commit/3570a09d9beadc008b5c5de7b1b15ecd6297143c).

**Comment by RobDangerous** [comment]
chokidar is the dependency responsible for watching for file changes, see if updating that helps.

**Comment by carlito767** [comment]
I updated all modules (including chokidar 2.0.4) but same issue.
Could you confirm you have the problem (to be sure it's not only on my side)?

**Comment by RblSb** [comment]
The last working commit for you is [this](https://github.com/Kode/khamake/commit/668fdaaec20592eee3fd844de9003d79a4dec00e)?

**Comment by carlito767** [comment]
Yes.

**Comment by RblSb** [comment]
@carlito767 You can try install old chokidar version and set it in package.json for latest khamake, perhaps it will give some results.

**Comment by carlito767** [comment]
When I come back to chokidar@1.7.0, it works. But it fails with the next release (chokidar@2.0.0).

**Comment by RobDangerous** [comment]
I can not reproduce your problems but this is a good data point. I'll look into removing chokidar, it also has problems with specific chars in paths which haven't been fixed in years.

**Comment by RblSb** [comment]
@carlito767 You might want to check 15 chockidar commits to identify the problem (this is 4 tests if you start from the middle of the groups)
https://github.com/paulmillr/chokidar/compare/1.7.0...2.0.0
If you find, report the issue in their repo.

**Comment by RblSb** [comment]
Also, try this khamake branch https://github.com/RblSb/khamake/tree/chokidar_fix

**Comment by RblSb** [comment]
I found that chokidar 2.0 supports only posix slashes, so this actually should help.

**Comment by carlito767** [comment]
I tried your fix and it works! Thanks!
