### ISSUE TITLE
Automate kha_version define

### ISSUE THREAD

**Issue by luboslenco** [Kode/khamake#169]
There is a `kha_version` defined at:
https://github.com/Kode/khamake/blob/master/src/main.ts#L105

However it does not always get updated on Kha changes. Somehow automating it per commit would be handy.

```haxe
#if (kha_version >= commit_xyz)
// Do new thing
#else
// Do old thing
#end
```

**Comment by RobDangerous** [comment]
But commits in git do not have a well defined order, a >= isn't really possible. I think the best solution would be a bot that adds a version commit once per month.

**Comment by luboslenco** [comment]
Yes the commit_xyz thing was a just silly example. Even a monthly auto-update would be great.

**Comment by RobDangerous** [comment]
krab (with a small k like all the command line tools) just uses --depth 3 for all _bin repos, pretty simple. Starting with 2019 I plan to use yearly branches for the bin repos so regular clones are also getting faster. Also looked into git-lfs to speed things up but sadly it's horrible on github (but could just use bitbucket for the bin repos) and hard to install on macOS.
But, yes, not too happy about people using kha_version defines anyways but not sure about just getting rid of it either.

**Comment by luboslenco** [comment]
The fastest way I found so far, if you only need shallow copy to start with:
`git clone --recursive https://github.com/Kode/Kha --depth 1 --shallow-submodules --jobs 4`

This finishes in ~80 seconds for me, of which haxe_bin takes up to 40 seconds. Once haxe3 is out it could maybe fit into 1 minute which is reasonable.
