### ISSUE TITLE
addAssets('../Assets/**') not including files

### ISSUE THREAD

**Issue by luboslenco** [Kode/khamake#193]
Does not work (files not added):
`project.addAssets('../Assets/**');`

Does work:
`project.addAssets('../Assets/image.png');`

It used to work at some point, will try to investigate further.

**Comment by RobDangerous** [comment]
That's about the ../ somehow?

**Comment by luboslenco** [comment]
Yes. `project.addAssets('Assets/**');` works. Maybe I am missing something?

**Comment by RobDangerous** [comment]
Never tried that. Have to test whether the glob thing handles it correctly first.
