### ISSUE TITLE
Add option to run a command before or after the compilation

### ISSUE THREAD

**Issue by caiopsouza** [Kode/khamake#81]
This is particularly useful when using the `--watch` option so everything run automatically.

**Comment by wighawag** [comment]
maybe this would solve this in a general way :  https://github.com/KTXSoftware/khamake/issues/34

**Comment by RobDangerous** [comment]
You can now set:

callbacks.preAssetConversion
callbacks.preShaderCompilation
callbacks.preHaxeCompilation
callbacks.postHaxeCompilation
callbacks.postCppCompilation

They are called in this order.
