### ISSUE TITLE
Option to khafile for specifying icon(s)

### ISSUE THREAD

**Issue by jefvel** [Kode/khamake#86]
Could be along the lines of

    project.addIcon(iconPath) 
    or
    project.addIcon(iconSize, iconPath);
    or
    project.options.icons = [{size:"x-large", path: iconPath}, {iconPath:iconPath}];
    or
    something else

**Comment by RobDangerous** [comment]
You can already drop an icon.png in your project dir and khamake will automatically pick it up.

**Comment by RblSb** [comment]
Closed with #180

**Comment by RblSb** [comment]
That guy is right

**Comment by RobDangerous** [comment]
Aye, cool dude 👍
