### ISSUE TITLE
Only seeing a black screen on Unity export.

### ISSUE THREAD

**Issue by jeremyfa** [Kode/khamake#92]
Hi, I am playing with Kha, which looks great so far!

Unfortunately, I am running into issues when trying to export to Unity:

First, I had to do some quick fixes on khamake files to workaround this issue: https://github.com/Kode/khamake/issues/74

Then, I did not succeed to get anything displayed on the Unity export. It just shows a black screen when running.

I tried with some basic lewis lepton's https://github.com/lewislepton/kha-tutorial-series examples (004_loadingImage and 005_drawingShape) with no luck.

The same examples work fine on html5, ios or mac export.

I am using latest Kha (git version) and latest Unity (5.5).

Am I missing something? Is there any other required step to make it work on Unity?

Thanks!

Edit: not sure if I should have posted this on Kha or khamake repository.

**Comment by RobDangerous** [comment]
Currently you'd have to downgrade to an older Kha revision. Have to do some updates to the shader compiler to get it working again...

**Comment by jeremyfa** [comment]
I see, thanks for the feedback!

Do you know which older version/commit of Kha I should use if I want to make it work on Unity?

**Comment by RobDangerous** [comment]
You can give https://github.com/Kode/Kha/commit/0eb1ae18df513d76594fd1cfb1df02be8b56b669#diff-e2aff9328f2f36d0ec21b3cccb596a03 a go but it's pretty old.

**Comment by jeremyfa** [comment]
Thanks! I will give it a try just to see if unity export works, but will stick with latest version otherwise anyway!

**Comment by RobDangerous** [comment]
If you run into problems due to the changes which happened meanwhile try an older revision of one of the samples, for example https://github.com/Kha-Samples/BlocksFromHeaven/commit/ad269f26a180f22eff7cc8c9aa061f73642f9f65

**Comment by jeremyfa** [comment]
Unfortunately I did not succeed to make any project work with previous or newer version of Kha, including your sample above. Not being familiar with Unity is not helping.

For now I guess I will stick to latest Kha and only use other targets (that work perfectly fine), until Unity backend gets up to date with newer Kha!

Thanks for the help anyway!

**Comment by RobDangerous** [comment]
One more hint - there's a Kha menu in Unity which you have to use once to initialize a new project.

**Comment by jeremyfa** [comment]
Ah, thanks! I will give it a try when I get back in front of a computer ;)

**Comment by jeremyfa** [comment]
Well, still no luck. On current kha (which gives black screen), I see the Kha menu and initializing it seems to add a component that loads the UnityBackend script, but then still black screen. Tried on your BlocksFromHeaven commit and got this error when opening Unity:

```
(...)/Backends/Unity/kha/audio1/UnitySoundChannel.hx(29,44): error CS0117: `UnityBackend' does not contain a definition for `loadSound'
```

(And Kha menu is not there)

I could continue tinkering and try to find out what is going on, but I don't really wish to debug this at the moment, especially on an older version of Kha. I'd rather wait until the target is "officially" working again to try one more time!

(That's ok, I was mostly _trying_ to run an example just to see how it goes, but I don't need Unity backend at the moment. That may, however, be a requirement that may come later if I use Kha so I am definitely interested to know when it will be working again)

**Comment by RobDangerous** [comment]
OK, moving it up on my todo list.

**Comment by RobDangerous** [comment]
Moved it way down on my todo-list at some point by discontinuing Unity-support. Sorry.
